In [89]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from  sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
import warnings

warnings.filterwarnings('ignore')

#Import Libraries and row dataset

In [90]:
df = pd.read_csv("loan_approval_dataset.csv")
df.head()

   loan_id   no_of_dependents  ...  bank_asset_value  loan_status
0        1                  2  ...           8000000     Approved
1        2                  0  ...           3300000     Rejected
2        3                  3  ...          12800000     Rejected
3        4                  3  ...           7900000     Rejected
4        5                  5  ...           5000000     Rejected

[5 rows x 13 columns]

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [92]:
df.describe()

           loan_id   no_of_dependents  ...   luxury_assets_value   bank_asset_value
count  4269.000000        4269.000000  ...          4.269000e+03       4.269000e+03
mean   2135.000000           2.498712  ...          1.512631e+07       4.976692e+06
std    1232.498479           1.695910  ...          9.103754e+06       3.250185e+06
min       1.000000           0.000000  ...          3.000000e+05       0.000000e+00
25%    1068.000000           1.000000  ...          7.500000e+06       2.300000e+06
50%    2135.000000           3.000000  ...          1.460000e+07       4.600000e+06
75%    3202.000000           4.000000  ...          2.170000e+07       7.100000e+06
max    4269.000000           5.000000  ...          3.920000e+07       1.470000e+07

[8 rows x 10 columns]

DATA PRE PROCESSING

In [93]:
df.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [94]:
df = df[[' no_of_dependents',' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status']]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    income_annum              4269 non-null   int64
 2    loan_amount               4269 non-null   int64
 3    loan_term                 4269 non-null   int64
 4    cibil_score               4269 non-null   int64
 5    residential_assets_value  4269 non-null   int64
 6    commercial_assets_value   4269 non-null   int64
 7    luxury_assets_value       4269 non-null   int64
 8    bank_asset_value          4269 non-null   int64
 9    loan_status               4269 non-null   object
dtypes: int64(9), object(1)
memory usage: 333.6+ KB

In [95]:
df['total_assets_values'] = df[' residential_assets_value'] + df[' commercial_assets_value'] + df[' luxury_assets_value'] + df[ ' bank_asset_value']
df.head()

    no_of_dependents   income_annum  ...   loan_status  total_assets_values
0                  2        9600000  ...      Approved             50700000
1                  0        4100000  ...      Rejected             17000000
2                  3        9100000  ...      Rejected             57700000
3                  3        8200000  ...      Rejected             52700000
4                  5        9800000  ...      Rejected             55000000

[5 rows x 11 columns]

In [96]:
df = df[[' no_of_dependents',' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' loan_status','total_assets_values']]
df

       no_of_dependents   income_annum  ...   loan_status  total_assets_values
0                     2        9600000  ...      Approved             50700000
1                     0        4100000  ...      Rejected             17000000
2                     3        9100000  ...      Rejected             57700000
3                     3        8200000  ...      Rejected             52700000
4                     5        9800000  ...      Rejected             55000000
...                 ...            ...  ...           ...                  ...
4264                  5        1000000  ...      Rejected              7400000
4265                  0        3300000  ...      Approved             20000000
4266                  2        6500000  ...      Rejected             39000000
4267                  1        4100000  ...      Approved             28800000
4268                  1        9200000  ...      Approved             77300000

[4269 rows x 7 columns]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0    no_of_dependents    4269 non-null   int64
 1    income_annum        4269 non-null   int64
 2    loan_amount         4269 non-null   int64
 3    loan_term           4269 non-null   int64
 4    cibil_score         4269 non-null   int64
 5    loan_status         4269 non-null   object
 6   total_assets_values  4269 non-null   int64
dtypes: int64(6), object(1)
memory usage: 233.6+ KB

In [98]:
df[' loan_status'].value_counts()

 loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [99]:
df[' loan_status'] = df[' loan_status'].str.lower().str.strip()

In [100]:
df

       no_of_dependents   income_annum  ...   loan_status  total_assets_values
0                     2        9600000  ...      approved             50700000
1                     0        4100000  ...      rejected             17000000
2                     3        9100000  ...      rejected             57700000
3                     3        8200000  ...      rejected             52700000
4                     5        9800000  ...      rejected             55000000
...                 ...            ...  ...           ...                  ...
4264                  5        1000000  ...      rejected              7400000
4265                  0        3300000  ...      approved             20000000
4266                  2        6500000  ...      rejected             39000000
4267                  1        4100000  ...      approved             28800000
4268                  1        9200000  ...      approved             77300000

[4269 rows x 7 columns]

In [101]:
df[' loan_status'] = df[' loan_status'].replace({'rejected' : 0,'approved' : 1}).astype(int)

df

       no_of_dependents   income_annum  ...   loan_status  total_assets_values
0                     2        9600000  ...             1             50700000
1                     0        4100000  ...             0             17000000
2                     3        9100000  ...             0             57700000
3                     3        8200000  ...             0             52700000
4                     5        9800000  ...             0             55000000
...                 ...            ...  ...           ...                  ...
4264                  5        1000000  ...             0              7400000
4265                  0        3300000  ...             1             20000000
4266                  2        6500000  ...             0             39000000
4267                  1        4100000  ...             1             28800000
4268                  1        9200000  ...             1             77300000

[4269 rows x 7 columns]

train test split

In [102]:
X = df.drop([' loan_status'], axis=1)
y = df[' loan_status']

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [104]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3415 entries, 1675 to 860
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0    no_of_dependents    3415 non-null   int64
 1    income_annum        3415 non-null   int64
 2    loan_amount         3415 non-null   int64
 3    loan_term           3415 non-null   int64
 4    cibil_score         3415 non-null   int64
 5   total_assets_values  3415 non-null   int64
dtypes: int64(6)
memory usage: 186.8 KB

In [105]:
X_train.shape

(3415, 6)

In [106]:
X_train.head()

       no_of_dependents   income_annum  ...   cibil_score  total_assets_values
1675                  5        7900000  ...           568             44300000
1164                  0        9600000  ...           710             80000000
192                   1         800000  ...           682              6900000
910                   2        4900000  ...           754             35200000
567                   5        3000000  ...           441             20300000

[5 rows x 6 columns]

In [107]:
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [108]:
y_pred = model.predict(X_test)

In [109]:
accuracy = accuracy_score(y_test,y_pred)

In [110]:
accuracy

0.797423887587822

In [111]:
new_application = pd.DataFrame([{
    " no_of_dependents" : 5,
    " income_annum" : 2500000,
    " loan_amount" : 8000000,
    " loan_term" : 15,
    " cibil_score" : 800,
    "total_assets_values" : 125000000  
}])

In [112]:
prediction = model.predict(new_application)

In [113]:
probability = model.predict_proba(new_application)

In [114]:
probability

array([[0.03219098, 0.96780902]])

In [115]:
prediction

array([1])