In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [4]:
df = pd.read_csv('Mall_Customers.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [11]:
df['Gender'].value_counts()

Gender
Female    112
Male       88
Name: count, dtype: int64

In [12]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [13]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    male   19                  15                      39
1           2    male   21                  15                      81
2           3  female   20                  16                       6
3           4  female   23                  16                      77
4           5  female   31                  17                      40

In [17]:
X = df.drop(['CustomerID'],axis = 1)

In [25]:
X

     Gender  Age  Annual Income (k$)  Spending Score (1-100)
0      male   19                  15                      39
1      male   21                  15                      81
2    female   20                  16                       6
3    female   23                  16                      77
4    female   31                  17                      40
..      ...  ...                 ...                     ...
195  female   35                 120                      79
196  female   45                 126                      28
197    male   32                 126                      74
198    male   32                 137                      18
199    male   30                 137                      83

[200 rows x 4 columns]